name: Deploy
on:
  push:
    # branches:
    #   - main

jobs:
  push-to-registry:
    name: Push to DockerHub Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/google-home-iot .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/google-home-iot

  deploy:
    name: Deploy production environment to AWS EC2
    runs-on: ubuntu-latest
    needs: push-to-registry
    steps:
      - name: Save SSH private key to file
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key
          chmod 400 private_key

      - name: Deploy to Azure VM and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ vars.AWS_VM_USER }}@${{ vars.AWS_VM_IP }} "\
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/google-home-iot || true && \
            sudo docker stop google-home-iot || true && \
            sudo docker rm google-home-iot || true && \
            sudo docker run --log-opt labels=applications,environment --restart unless-stopped --name google-home-iot -e AZURE_IOT_HUB_CONNECTION_STRING='${{ secrets.AZURE_IOT_HUB_CONNECTION_STRING }}' -d -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/google-home-iot"
